### ISSUE TITLE
RoleRelativePath.py fails when 'src' is not provided in copy task

### ISSUE THREAD

**Issue by nkarpin** [tsukinowasha/ansible-lint-rules#1]
I have this task:

```
- name: Copy content to file
copy:
    content: "{{ some_content }}"
    dest: "{{ some_dest }}"
    owner: username
    group: username
    mode: 0400
```

When i launch ansible-lint on this task using your rules I get:

Traceback (most recent call last):
  File "/tmp/workspace_lint/.tox/bin/ansible-lint", line 135, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/tmp/workspace_lint/.tox/bin/ansible-lint", line 122, in main
    matches.extend(runner.run())
  File "/tmp/workspace_lint/.tox/local/lib/python2.7/site-packages/ansiblelint/**init**.py", line 239, in run
    skip_list=set(self.skip_list)))
  File "/tmp/workspace_lint/.tox/local/lib/python2.7/site-packages/ansiblelint/**init**.py", line 141, in run
    matches.extend(rule.matchyaml(playbookfile, text))
  File "/tmp/workspace_lint/.tox/local/lib/python2.7/site-packages/ansiblelint/**init**.py", line 90, in matchyaml
    result = self.matchplay(file, play)
  File ".tox/rules/rules/RoleRelativePath.py", line 31, in matchplay
    if "../copys" in play['copy']['src']:
KeyError: 'src'

It looks like we need to check if 'src' field is present in copy
