### ISSUE TITLE
skip_ansible_lint does not work with this action.

### ISSUE THREAD

**Issue by bbaassssiiee** [tsukinowasha/ansible-lint-rules#5]
```
- name: 'configure postgres_net to postgres_port in firewalld'
  become: yes
  firewalld: rich_rule='rule family="ipv4" source address="{{ postgres_net }}" port port="{{ postgres_port }}" protocol="tcp" accept' permanent=true state=enabled immediate=yes
  tags:
    - skip_ansible_lint
```
